.TH MYSTRLEN 3 "September 2026" "libmyutils" "Library Functions"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.PP
.B int mystrlen(const char *s);
.SH DESCRIPTION
.B mystrlen
calculates the number of characters in the string
.BR s ,
excluding the terminating null character.
.SH RETURN VALUE
Returns the length of the string.
.SH AUTHOR
Mujtaba Raza
