.TH MYSTRCPY 3 "September 2026" "libmyutils" "Library Functions"
.SH NAME
mystrcpy \- copy a string into a destination
.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.PP
.B int mystrcpy(char *dest, const char *src);
.SH DESCRIPTION
.B mystrcpy
copies the string
.BR src
into the destination string
.BR dest ,
including the terminating null character.
.SH RETURN VALUE
Returns the number of characters copied, excluding the terminating null character.
.SH AUTHOR
Mujtaba Raza
